[package]
name = "back-end"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-multipart = "0.7"
utoipa = { version = "5", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "8", features = ["actix-web"] }
utoipa-actix-web = "0.1"
env_logger = "0.10"  # Adicione esta linha
log = "0.4"          # Necessária para integração de logs
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15"
reqwest = { version = "0.11", features = ["json"] }
actix-cors = "0.6"
stellar_sdk = "0.1.4"  # Versão mais recente que suporta Stellar
aes-gcm = "0.10"       # Para criptografia AES-128-GCM
rand = "0.8"           # Para geração de números aleatórios
base64 = "0.21"        # Para codificação/decodificação Base64
serde_json = "1.0"



[workspace]