# Etapa 1: Build da aplicação
FROM rust:1.75 as builder

# Atualizar Cargo antes de compilar
RUN rustup update stable && rustup default stable

# Definir diretório de trabalho
WORKDIR /app

# Copiar arquivos do projeto
COPY Cargo.toml Cargo.lock ./
COPY src ./src

# Compilar a aplicação
RUN cargo build --release
